Create a `Results` class for storing metric output with associated metadata
Janelia-Trackathon-2023/traccuracy pull request #126
Opened 2023-11-28 22:55 UTC by msschwartz21

# Proposed Change
Closes #120 

# Types of Changes
What types of changes does your code introduce? Put an x in the boxes that apply.
- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature or enhancement
- [ ] Documentation update
- [ ] Tests and benchmarks
- [ ] Maintenance (e.g. dependencies, CI, releases, etc.)

Which topics does your change affect? Put an x in the boxes that apply.
- [ ] Loaders
- [ ] Matchers
- [ ] Track Errors
- [x] Metrics
- [ ] Core functionality (e.g. `TrackingGraph`, `run_metrics`, `cli`, etc.)

# Checklist
Put an x in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code.

- [ ] I have read the developer/contributing docs.
- [ ] I have added tests that prove that my feature works in various situations or tests the bugfix (if appropriate).
- [ ] I have checked that I maintained or improved code coverage.
- [ ] I have checked the benchmarking action to verify that my changes did not adversely affect performance.
- [ ] I have written docstrings and checked that they render correctly in the Read The Docs build (created after the PR is opened).
- [ ] I have updated the general documentation including Metric descriptions and example notebooks if necessary.

2023-11-29 20:35 UTC, cmalinmayor requested changes

2023-11-29 20:35 UTC, cmalinmayor commented on src/traccuracy/metrics/_base.py
> +        matcher_info: dict | None = None,
Results, matcher_info, and metric_info can be required and always included in the to_dict

2023-11-29 20:35 UTC, cmalinmayor commented on tests/matchers/test_base.py
> +    assert "param" in matcher.info
Also test that the default value is present? And/or that if you initialize with not the default, it changes?

2023-11-29 20:35 UTC, cmalinmayor commented on tests/test_run_metrics.py
> +    print(results)
remove debugging print!

2023-11-29 20:58 UTC, cmalinmayor approved these changes
Perfect! Thanks Morgan 🎊

2023-11-29 20:58 UTC, cmalinmayor commented
Wait except all the tests failing @msschwartz21 😬

2023-11-30 00:33 UTC, msschwartz21 commented
> Wait except all the tests failing @msschwartz21 😬

I was being spacey... Should be ok now 🤞

2023-11-30 16:13 UTC, cmalinmayor commented
@bentaculum Just warning you about these changes because I know you have built code on top of traccuracy output, and we plan to wrap that results dictionary in a class, so this will be a breaking change for you I suspect.

2023-12-15 18:46 UTC, merged